### ISSUE TITLE
结果跑出来准确率并不是很高啊，什么原因

### ISSUE THREAD

**Issue by wangtao666666** [keavil/AAAI18-code#11]
![2018-11-30 10 16 42](https://user-images.githubusercontent.com/32592839/49264401-11bb8900-f489-11e8-92fd-9e1564c07cd1.png)
training : total  19 nodes.
LSTM_only  0 ----test:  0.1 | dev:  0.1
training : total  19 nodes.
LSTM_only  1 ----test:  0.3 | dev:  0.3
LSTM pretrain OK
epsilon 0.05
training : total  19 nodes.
RL pretrain  0 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  1 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  2 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  3 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  4 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  5 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  6 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  7 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  8 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  9 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  10 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  11 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  12 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  13 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  14 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  15 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  16 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  17 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  18 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
RL pretrain  19 ----test:  0.3 | dev:  0.3
RL pretrain OK
training : total  19 nodes.
epoch  0 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
epoch  1 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
epoch  2 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
epoch  3 ----test:  0.3 | dev:  0.3
training : total  19 nodes.
epoch  4 ----test:  0.0 | dev:  0.0

Process finished with exit code 0

**Comment by wangtao666666** [comment]
AG数据集合，哪里出问题啦嘛

**Comment by wangtao666666** [comment]
数据集
AG:https://drive.google.com/open?id=1becf7pzfuLL7qgWqv4q-TyDYjSzodWfR
词向量：GLOVE 300维词向量语料，为什么差这么多

**Comment by scofield7419** [comment]
> AG数据集合，哪里出问题啦嘛

我的跑出来的是符合论文中的指标的。
你使用了fasttest，试试把：
`        parser.add_argument('--fasttest', type=int, default=0, choices=[0, 1])
`
设为0，使用全量数据训练.

**Comment by wangtao666666** [comment]
> > AG数据集合，哪里出问题啦嘛
> 
> 我的跑出来的是符合论文中的指标的。
> 你使用了fasttest，试试把：
> ` parser.add_argument('--fasttest', type=int, default=0, choices=[0, 1])`
> 设为0，使用全量数据训练.

👌的，谢谢，还有一个问题action定义为1是保留操作吧,定义为0是删除操作

**Comment by YMMY22** [comment]
你好，我想问一下代码里，datamanager.py文件中get_vector()函数的参数，vector.25dim文件你是从哪里找到的，我找了好久都没找到。如果可以的话，麻烦发给我一下，我的Email：659640300@qq.com，十分感谢！

**Comment by MENGHAH** [comment]
> ![2018-11-30 10 16 42](https://user-images.githubusercontent.com/32592839/49264401-11bb8900-f489-11e8-92fd-9e1564c07cd1.png)
> training : total 19 nodes.
> LSTM_only 0 ----test: 0.1 | dev: 0.1
> training : total 19 nodes.
> LSTM_only 1 ----test: 0.3 | dev: 0.3
> LSTM pretrain OK
> epsilon 0.05
> training : total 19 nodes.
> RL pretrain 0 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 1 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 2 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 3 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 4 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 5 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 6 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 7 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 8 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 9 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 10 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 11 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 12 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 13 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 14 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 15 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 16 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 17 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 18 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> RL pretrain 19 ----test: 0.3 | dev: 0.3
> RL pretrain OK
> training : total 19 nodes.
> epoch 0 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> epoch 1 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> epoch 2 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> epoch 3 ----test: 0.3 | dev: 0.3
> training : total 19 nodes.
> epoch 4 ----test: 0.0 | dev: 0.0
> 
> Process finished with exit code 0
你好，我想问一下你是否明白代码Actor.py里面的input_l和input_d都代表什么吗？

**Comment by MENGHAH** [comment]
Traceback (most recent call last):
  File "datamanager.py", line 106, in <module>
    train_data, test_data, dev_data = datamanager.getdata(2, 200)
  File "datamanager.py", line 74, in getdata
    solution = one_hot_vector(int(sent['rating']))
  File "datamanager.py", line 53, in one_hot_vector
    s[r] += 1.0
IndexError: index 3 is out of bounds for axis 0 with size 2
我在执行datamanager.py的文件时出现了以上错误，不知道前辈们有没有遇到过，是怎么解决的？

**Comment by Maigewm** [comment]
您好，请问您的问题最终解决了没有？关于代码部分我有一些疑惑，请问可以联系您解答吗？我的邮箱是411466357@qq.com，万分感谢！

**Comment by Maigewm** [comment]
您好，请问您的问题最终解决了没有？关于代码部分我有一些疑惑，请问可以联系您解答吗？我的邮箱是411466357@qq.com，万分感谢！
