### ISSUE TITLE
关于异常

### ISSUE THREAD

**Issue by whu20122015** [keavil/AAAI18-code#3]
您好,用您的代码运行的时候出现以下异常，请问应该怎么处理呢？
Traceback (most recent call last):
  File "/home/chenjiafeng/Desktop/5.2/AAAI18-code-master/ID_LSTM/main.py", line 21, in <module>
    train_data, dev_data, test_data = dataManager.getdata(args.grained, args.maxlenth)
  File "/home/chenjiafeng/Desktop/5.2/AAAI18-code-master/ID_LSTM/datamanager.py", line 72, in getdata
    solution = one_hot_vector(int(sent['rating']))
  File "/home/chenjiafeng/Desktop/5.2/AAAI18-code-master/ID_LSTM/datamanager.py", line 52, in one_hot_vector
    s[r] += 1.0
IndexError: index 3 is out of bounds for axis 0 with size 2

**Comment by keavil** [comment]
你需要修改一下parser中grained这个参数，代表数据集有几个类别。

**Comment by whu20122015** [comment]
好的 多谢~
